"""Workflow operators."""

from .landmarks import LANDMARK_OPERATOR_CLASSES
from .rigging import RIGGING_OPERATOR_CLASSES
from .workflow import OPERATOR_CLASSES as WORKFLOW_OPERATOR_CLASSES

OPERATOR_CLASSES = (
    LANDMARK_OPERATOR_CLASSES
    + WORKFLOW_OPERATOR_CLASSES
    + RIGGING_OPERATOR_CLASSES
)

__all__ = ("OPERATOR_CLASSES",)
