"""Workflow operators."""

from .intake import INTAKE_OPERATOR_CLASSES
from .landmarks import LANDMARK_OPERATOR_CLASSES
from .rigging import RIGGING_OPERATOR_CLASSES
from .source_doctor import SOURCE_DOCTOR_OPERATOR_CLASSES
from .texture_repair import TEXTURE_REPAIR_OPERATOR_CLASSES
from .workflow import OPERATOR_CLASSES as WORKFLOW_OPERATOR_CLASSES

OPERATOR_CLASSES = (
    INTAKE_OPERATOR_CLASSES
    + LANDMARK_OPERATOR_CLASSES
    + SOURCE_DOCTOR_OPERATOR_CLASSES
    + TEXTURE_REPAIR_OPERATOR_CLASSES
    + WORKFLOW_OPERATOR_CLASSES
    + RIGGING_OPERATOR_CLASSES
)

__all__ = ("OPERATOR_CLASSES",)
